"""store ai grounding context

Revision ID: 179c4b6caf5a
Revises: f6be086e0c85
Create Date: 2026-08-17 20:41:28.232503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '179c4b6caf5a'
down_revision: Union[str, Sequence[str], None] = 'f6be086e0c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigation_reports', sa.Column('grounding_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigation_reports', 'grounding_json')
    # ### end Alembic commands ###