"""add analysis ownership

Revision ID: 6b23cda6ee4f
Revises: eaa1ec44380a
Create Date: 2026-08-04 16:37:09.129029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6b23cda6ee4f'
down_revision: Union[str, Sequence[str], None] = 'eaa1ec44380a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_records', sa.Column('owner_user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_analysis_records_owner_user_id'), 'analysis_records', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'analysis_records', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_records', type_='foreignkey')
    op.drop_index(op.f('ix_analysis_records_owner_user_id'), table_name='analysis_records')
    op.drop_column('analysis_records', 'owner_user_id')
    # ### end Alembic commands ###