"""add threat intelligence cache

Revision ID: 7500f428120d
Revises: 179c4b6caf5a
Create Date: 2026-08-18 21:15:00.986682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7500f428120d'
down_revision: Union[str, Sequence[str], None] = '179c4b6caf5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_intel_enrichment_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('indicator_type', sa.String(length=30), nullable=False),
    sa.Column('indicator_value', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'indicator_type', 'indicator_value', name='uq_threat_intel_provider_indicator')
    )
    op.create_index(op.f('ix_threat_intel_enrichment_record_indicator_type'), 'threat_intel_enrichment_record', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threat_intel_enrichment_record_indicator_value'), 'threat_intel_enrichment_record', ['indicator_value'], unique=False)
    op.create_index(op.f('ix_threat_intel_enrichment_record_provider'), 'threat_intel_enrichment_record', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_intel_enrichment_record_provider'), table_name='threat_intel_enrichment_record')
    op.drop_index(op.f('ix_threat_intel_enrichment_record_indicator_value'), table_name='threat_intel_enrichment_record')
    op.drop_index(op.f('ix_threat_intel_enrichment_record_indicator_type'), table_name='threat_intel_enrichment_record')
    op.drop_table('threat_intel_enrichment_record')
    # ### end Alembic commands ###