"""store investigation anomaly evidence

Revision ID: 762a32f24e5d
Revises: 8b96651c2c3f
Create Date: 2026-08-22 20:01:38.715883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '762a32f24e5d'
down_revision: Union[str, Sequence[str], None] = '8b96651c2c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigation_reports', sa.Column('anomaly_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigation_reports', 'anomaly_json')
    # ### end Alembic commands ###