"""add anomaly analysis runs

Revision ID: 8b96651c2c3f
Revises: de92a73a6ed5
Create Date: 2026-08-20 22:33:45.643852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8b96651c2c3f'
down_revision: Union[str, Sequence[str], None] = 'de92a73a6ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('contamination', sa.Float(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('analysed_events', sa.Integer(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_runs_analysis_id'), 'anomaly_runs', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_anomaly_runs_created_at'), 'anomaly_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_anomaly_runs_requested_by_user_id'), 'anomaly_runs', ['requested_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_runs_requested_by_user_id'), table_name='anomaly_runs')
    op.drop_index(op.f('ix_anomaly_runs_created_at'), table_name='anomaly_runs')
    op.drop_index(op.f('ix_anomaly_runs_analysis_id'), table_name='anomaly_runs')
    op.drop_table('anomaly_runs')
    # ### end Alembic commands ###