"""create analysis records table

Revision ID: 995503b8ad5c
Revises: 
Create Date: 2026-08-03 15:19:05.108943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '995503b8ad5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('ignored_lines', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_records_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_records_created_at'))

    op.drop_table('analysis_records')
    # ### end Alembic commands ###