"""store investigation threat intelligence

Revision ID: d3f0a53b61c3
Revises: 7500f428120d
Create Date: 2026-08-19 16:34:09.979340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd3f0a53b61c3'
down_revision: Union[str, Sequence[str], None] = '7500f428120d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigation_reports', sa.Column('threat_intel_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigation_reports', 'threat_intel_json')
    # ### end Alembic commands ###