"""add analyst cases

Revision ID: de92a73a6ed5
Revises: d3f0a53b61c3
Create Date: 2026-08-20 11:15:30.960549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'de92a73a6ed5'
down_revision: Union[str, Sequence[str], None] = 'd3f0a53b61c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_assigned_to_user_id'), 'cases', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_cases_created_by_user_id'), 'cases', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_cases_severity'), 'cases', ['severity'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('case_analysis_links',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('linked_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('case_id', 'analysis_id')
    )
    op.create_table('case_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_author_user_id'), 'case_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('case_timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('event_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_timeline_events_actor_user_id'), 'case_timeline_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_case_timeline_events_case_id'), 'case_timeline_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_timeline_events_created_at'), 'case_timeline_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_timeline_events_event_type'), 'case_timeline_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_timeline_events_event_type'), table_name='case_timeline_events')
    op.drop_index(op.f('ix_case_timeline_events_created_at'), table_name='case_timeline_events')
    op.drop_index(op.f('ix_case_timeline_events_case_id'), table_name='case_timeline_events')
    op.drop_index(op.f('ix_case_timeline_events_actor_user_id'), table_name='case_timeline_events')
    op.drop_table('case_timeline_events')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_index(op.f('ix_case_notes_author_user_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_table('case_analysis_links')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_severity'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_by_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_to_user_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###